"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var FTE_1 = require("./FTE");
var Contractor_1 = require("./Contractor");
var EmployeeController_1 = require("./EmployeeController");
var a = new FTE_1.default("A");
var b = new Contractor_1.default("B");
var c = new FTE_1.default("C");
var e = new FTE_1.default("E");
var d = new Contractor_1.default("D");
var sortedEmployee = EmployeeController_1.default.getSortedEmployee([a, b, c, d, e]);
console.log(sortedEmployee);
