"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var FTE_1 = require("./FTE");
var Contractor_1 = require("./Contractor");
var EmployeeController_1 = require("./EmployeeController");
var a = new FTE_1.default("A");
var b = new FTE_1.default("B");
var c = new FTE_1.default("C");
var d = new Contractor_1.default("D");
var e = new Contractor_1.default("E");
var totalSalary = EmployeeController_1.default.getTotalSalary([a, b, c, d, e]);
console.log("Total Salary: ".concat(totalSalary));
